### ISSUE TITLE
Pipfile python version

### ISSUE THREAD

**Issue by seandenigris** [aranega/pybridge#3]
Based on my limited research, it seems the conservative best practice is to stay one major version behind latest Python, which seems to be 3.8.6. Any reason to default to 3.7?

**Comment by aranega** [comment]
No, none, it's just a kind of side effect of `pipenv` that tries to "freeze" the state of the virtual env during dev (more or less). I started to work on PyBridge on my free time two years ago :grimacing: so... You can definitely change that.

I start to think that `pipenv` raise more questions than it solves issues in this project, I will check by what I can change it.
